app/Http/routes.php
<?php

/*
  |--------------------------------------------------------------------------
  | Routes File
  |--------------------------------------------------------------------------
  |
  | Here is where you will register all of the routes in an application.
  | It's a breeze. Simply tell Laravel the URIs it should respond to
  | and give it the controller to call when that URI is requested.
  |
 */

Route::get('/', function () {
    return view('welcome');
});

/*
  |--------------------------------------------------------------------------
  | Application Routes
  |--------------------------------------------------------------------------
  |
  | This route group applies the "web" middleware group to every route
  | it contains. The "web" middleware group is defined in your HTTP
  | kernel and includes session state, CSRF protection, and more.
  |
 */

Route::group(['middleware' => ['web']], function () {
    Route::get('/some/path', [
        'as' => 'my.example.get',
        'uses' => 'FirstController@getMethod'
    ]);
    Route::post('/some/post', [
        'as' => 'my.example.post',
        'uses' => 'FirstController@postMethod'
    ]);
    
   // Delete
    Route::get('/treeApp/{id}/delete',[
        'as' => 'treeApp.delete',
        'uses' => 'SecondController@delete'
    ]);
    
    Route::resource('treeApp', 'SecondController');
    
    // Language route
    Route::post('/treeApp/lang/example',[
        'as' => 'treeApp.lang',
        'uses' => 'SecondController@lang'
    ]);
    
    // Resource controller routes
    // 
   // Delete
    Route::get('/clients/{id}/delete',[
        'as' => 'clients.delete',
        'uses' => 'ResourceCtrl@delete'
    ]);
    
    Route::resource('clients', 'ResourceCtrl');
    
    Route::get('/clients/{id}/json',[
        'as' => 'clients.json',
        'uses' => 'ResourceCtrl@json'
    ]);
    
    Route::get('/clients/{id}/json-response',[
        'as' => 'clients.json.response',
        'uses' => 'ResourceCtrl@jsonResponse'
    ]);
});

app/Models/Client.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Client extends Model
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes excluded from the model's JSON form.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
    
    public function tasks(){
        return $this->hasMany('App\Models\Product');
    }
}

resources/views/pages/clients/create.blade.php
<!DOCTYPE html>
<html>
    <head>
        <title></title>
        <style>
            td{
                 border:1px solid #333;
                 padding:10px;
            }            
        </style>
    </head>
    <body>
        @include('pages.clients.partials.errors')
        <form action="{{route('clients.store')}}" method="post">
            <input style='color:red;' type="hidden" name="_token" value="{{ csrf_token() }}">
            <p>
                <label>Name</label>
                <input type="text" name="name" >                
            </p>
            <p>
                <label>User</label>
                <select name="client">
                    @foreach( $clients as $client)
                    <option value="{{ $client['id'] }}">{{ $client['name'] }}</option>
                    @endforeach
                </select>
            </p>
            <input type="submit">
        </form>
        
    </body>
</html>

resources/views/pages/clients/delete.blade.php
<!DOCTYPE html>
<html>
    <head>
        <title></title>
        <style>
            td{
                 border:1px solid #333;
                 padding:10px;
            }            
        </style>
    </head>
    <body>

        <form action="{{route('clients.destroy', $model['id'])}}" method="post">
            <input style='color:red;' type="hidden" name="_token" value="{{ csrf_token() }}">
            <input type="hidden" name="_method" value="delete">
            <p>
                <label>Are you sure to deleting this item:</label>
                {{ $model['name'] }}              
            </p>

            <input type="submit" value="Destroy">
        </form>
        
    </body>
</html>

resources/views/pages/clients/edit.blade.php
<!DOCTYPE html>
<html>
    <head>
        <title></title>
        <style>
            td{
                 border:1px solid #333;
                 padding:10px;
            }            
        </style>
    </head>
    <body>

        <form action="{{route('clients.update', $model['id'])}}" method="post">
            <input style='color:red;' type="hidden" name="_token" value="{{ csrf_token() }}">
            <input type="hidden" name="_method" value="put">
            <p>
                <label>Name</label>
                <input type="text" name="name" value="{{ $model['name'] }}" >                
            </p>
            <p>
                <label>User</label>
                <select name="client">
                    @foreach( $clients as $client)
                    <option 
                        @if($client['id'] === $model['client_id'] )
                            selected="selected"
                        @endif
                        value="{{ $client['id'] }}">
                        {{ $client['name'] }}
                    </option>
                    @endforeach
                </select>
            </p>
            <input type="submit" value="Update">
        </form>
        
    </body>
</html>

resources/views/pages/clients/included.blade.php
<div class="clearfix"></div>
<div class="jumbotron">
  <h2>I'm included included.jade</h2>
</div>

resources/views/pages/clients/index.blade.php
<!DOCTYPE html>
<html>
    <head>
        <title></title>
        <link href="{{ asset('vendor/bootstrap/css/bootstrap.css') }}" rel="stylesheet" />
        <link href="{{ asset('vendor/bootstrap/css/bootstrap-theme.css') }}" rel="stylesheet" />
        <link href="{{ asset('vendor/bootstrap/css/print.css') }}" rel="stylesheet" />
        <link href="{{ asset(elixir('css/example.css')) }}" rel="stylesheet" />
        <link href="{{ asset(elixir('css/antonStyle.css')) }}" rel="stylesheet" />

    </head>
    <body>
        <form action="{{ route('clients.index') }}" method="post">
            <label>Check to redirect</label>
            <input style='color:red;' type="hidden" name="_token" value="{{ csrf_token() }}">
            <input type="checkbox" name="redirect-checkbox">
            <input type="submit" value="Submit">
        </form>


        @if (Session::has('myMessage'))
        <h2>{{ Session::get('myMessage') }}</h2>
        @endif

        <table>
            <tr>
                <td>Id</td>
                <td>Name</td>
                <td>Client id</td>
                <td>Full name</td>
                <td>Action</td>
            </tr>
            @foreach( $models as $item)
            <tr>
                <td>{{$item['id']}}</td>
                <td>{{CleanString::removeSpecialChar($item['name'])}}</td>
                <td>{{$item['client_id']}}</td>
                <td>{{ $item['full_name'] }}</td>
                <td>
                    <a href="{{ route('clients.edit', $item['id']) }}">Edit</a>
                    <a href="{{ route('clients.delete', $item['id']) }}">Delete</a>
                </td>
            </tr>
            @endforeach            
        </table>
        <div class="mail-icon-wrapper">
            <span class="mail-icon glyphicon glyphicon-envelope"></span>
        </div>
        
        
        <h2><a class="btn btn-primary" href="{{route('clients.create')}}">Create a new product</a></h2>
        
        <div class="jumbotron">
            <div class="change-color btn btn-default">Change Color</div>
        </div>
        
        
        @include('pages/clients/testJade')
        
        
        <script type="text/javascript" src="{{ asset('vendor/jquery/js/jquery.js') }}"></script>
        <script type="text/javascript" src="{{ asset('vendor/bootstrap/js/bootstrap.js') }}"></script>
        <script type="text/javascript" src="{{ asset(elixir('js/layout.js')) }}"></script>
        <script type="text/javascript" src="{{ asset(elixir('js/antonScript.js')) }}"></script>
        <script type="text/javascript" >
            var JSON_PATH = "{{ route('clients.json',1 ) }}";
            var JSON_RESPONSE_PATH = "{{ route('clients.json.response',1 ) }}";
            var TOKEN = "{{ csrf_token() }}";
        </script>
    </body>
</html>

resources/views/pages/clients/show.blade.php
<!DOCTYPE html>
<html>
    <head>
        <title></title>
        <style>
            td{
                 border:1px solid #333;
                 padding:10px;
            }            
        </style>
    </head>
    <body>

<table>
    <tr>
        <td>Id</td>
        <td>Name</td>
        <td>User id</td>
    </tr>
    <tr>
        <td>{{$model['id']}}</td>
        <td>{{$model['name']}}</td>
        <td>{{$model['client_id']}}</td>
    </tr>

</table>

<table>
    <tr>
        <td>Id</td>
        <td>Name</td>
        <td>Email</td>
    </tr>
    <tr>
        <td>{{$model['client']['id']}}</td>
        <td>{{$model['client']['name']}}</td>
        <td>{{$model['client']['email']}}</td>
    </tr>

</table>
        
    </body>
</html>

resources/views/pages/clients/testJade.blade.php
<div class="clearfix"></div>
<div class="jumbotron">
  <div class="btn btn-success">This is included testJade.jade</div>
  <div class="clearfix"></div>
  <div>@if( 1 === 1)
    <h3>This part will appear if "IF" will be trues </h3>@endif
  </div>
</div>
<div class="clearfix"></div>@include('pages/clients/included')