app/Http/routes.php
<?php

/*
  |--------------------------------------------------------------------------
  | Routes File
  |--------------------------------------------------------------------------
  |
  | Here is where you will register all of the routes in an application.
  | It's a breeze. Simply tell Laravel the URIs it should respond to
  | and give it the controller to call when that URI is requested.
  |
 */

Route::get('/', function () {
    return view('welcome');
});

/*
  |--------------------------------------------------------------------------
  | Application Routes
  |--------------------------------------------------------------------------
  |
  | This route group applies the "web" middleware group to every route
  | it contains. The "web" middleware group is defined in your HTTP
  | kernel and includes session state, CSRF protection, and more.
  |
 */

Route::group(['middleware' => ['web']], function () {
    Route::get('/some/path', [
        'as' => 'my.example.get',
        'uses' => 'FirstController@getMethod'
    ]);
    Route::post('/some/post', [
        'as' => 'my.example.post',
        'uses' => 'FirstController@postMethod'
    ]);
    
   // Delete
    Route::get('/treeApp/{id}/delete',[
        'as' => 'treeApp.delete',
        'uses' => 'SecondController@delete'
    ]);
    
    Route::resource('treeApp', 'SecondController');
    
    // Language route
    Route::post('/treeApp/lang/example',[
        'as' => 'treeApp.lang',
        'uses' => 'SecondController@lang'
    ]);
    
    // Resource controller routes
    // 
   // Delete
    Route::get('/clients/{id}/delete',[
        'as' => 'clients.delete',
        'uses' => 'ResourceCtrl@delete'
    ]);
    
    Route::resource('clients', 'ResourceCtrl');
    
    Route::get('/clients/{id}/json',[
        'as' => 'clients.json',
        'uses' => 'ResourceCtrl@json'
    ]);
    
    Route::get('/clients/{id}/json-response',[
        'as' => 'clients.json.response',
        'uses' => 'ResourceCtrl@jsonResponse'
    ]);
});

resources/views/pages/create.blade.php
<!DOCTYPE html>
<html>
    <head>
        <title></title>
        <style>
            td{
                 border:1px solid #333;
                 padding:10px;
            }            
        </style>
    </head>
    <body>
        @include('pages.partials.errors')
        
        <form action="{{route('treeApp.store')}}" method="post">
            <input style='color:red;' type="hidden" name="_token" value="{{ csrf_token() }}">
            <p>
                <label>Name</label>
                <input type="text" name="name" >                
            </p>
            <p>
                <label>User</label>
                <select name="user">
                    @foreach( $users as $user)
                    <option value="{{ $user['id'] }}">{{ $user['name'] }}</option>
                    @endforeach
                </select>
            </p>
            <input type="submit">
        </form>
        
    </body>
</html>

resources/views/pages/delete.blade.php
<!DOCTYPE html>
<html>
    <head>
        <title></title>
        <style>
            td{
                 border:1px solid #333;
                 padding:10px;
            }            
        </style>
    </head>
    <body>

        <form action="{{route('treeApp.destroy', $model['id'])}}" method="post">
            <input style='color:red;' type="hidden" name="_token" value="{{ csrf_token() }}">
            <input type="hidden" name="_method" value="delete">
            <p>
                <label>Are you sure to deleting this item:</label>
                {{ $model['name'] }}              
            </p>

            <input type="submit" value="Destroy">
        </form>
        
    </body>
</html>

resources/views/pages/edit.blade.php
<!DOCTYPE html>
<html>
    <head>
        <title></title>
        <style>
            td{
                 border:1px solid #333;
                 padding:10px;
            }            
        </style>
    </head>
    <body>

        <form action="{{route('treeApp.update', $model['id'])}}" method="post">
            <input style='color:red;' type="hidden" name="_token" value="{{ csrf_token() }}">
            <input type="hidden" name="_method" value="put">
            <p>
                <label>Name</label>
                <input type="text" name="name" value="{{ $model['name'] }}" >                
            </p>
            <p>
                <label>User</label>
                <select name="user">
                    @foreach( $users as $user)
                    <option 
                        @if($user['id'] === $model['user_id'] )
                            selected="selected"
                        @endif
                        value="{{ $user['id'] }}">{{ $user['name'] }}</option>
                    @endforeach
                </select>
            </p>
            <input type="submit" value="Update">
        </form>
        
    </body>
</html>

resources/views/pages/mainView.blade.php
<!DOCTYPE html>
<html>
    <head>
        <title></title>
        <style>
            td{
                 border:1px solid #333;
                 padding:10px;
            }            
        </style>
    </head>
    <body>

        @if (Session::has('myMessage'))
        <h2>{{ Session::get('myMessage') }}</h2>
        @endif
        
        <table>
            <tr>
                <td>Id</td>
                <td>Name</td>
                <td>User id</td>
            </tr>
            @foreach( $models as $item)
            <tr>
                <td>{{$item['id']}}</td>
                <td>{{$item['name']}}</td>
                <td>{{$item['user_id']}}</td>
                <td>{{ $item['full_name'] }}</td>
                <td>
                    <a href="{{ route('treeApp.edit', $item['id']) }}">Edit</a>
                    <a href="{{ route('treeApp.delete', $item['id']) }}">Delete</a>
                </td>
            </tr>
            @endforeach            
        </table>

    </body>
</html>

resources/views/pages/show.blade.php
<!DOCTYPE html>
<html>
    <head>
        <title></title>
        <style>
            td{
                 border:1px solid #333;
                 padding:10px;
            }            
        </style>
    </head>
    <body>

<table>
    <tr>
        <td>Id</td>
        <td>Name</td>
        <td>User id</td>
    </tr>
    <tr>
        <td>{{$model['id']}}</td>
        <td>{{$model['name']}}</td>
        <td>{{$model['user_id']}}</td>
    </tr>

</table>

<table>
    <tr>
        <td>Id</td>
        <td>Name</td>
        <td>Email</td>
    </tr>
    <tr>
        <td>{{$model['user']['id']}}</td>
        <td>{{$model['user']['name']}}</td>
        <td>{{$model['user']['email']}}</td>
    </tr>

</table>
        
    </body>
</html>